### PR TITLE
custom field for user images

### PR DESCRIPTION
**Pull request by leonoragilmour**
sorry this was unnecessarily fiddly... but new acf field for user pics

```js
"_embedded":{
  "author":[
    {
      "id":109,
      "name":"leogilmour",
      "url":"",
      "description":"",
      "link":"https://shortlist.studio/author/leogilmour",
      "slug":"leogilmour",
      "avatar_urls":{

      },
      "acf":{
        "user_image":{
          "ID":324982,
          "id":324982,
          "title":"54e80dd703fb02d789b1179fa8fdbcaa.png",
          "filename":"54e80dd703fb02d789b1179fa8fdbcaa.png",
          "url":"http://assets-cdn.shortlist.com/app/uploads/2017/09/11151738/54e80dd703fb02d789b1179fa8fdbcaa.png",
          "alt":"",
          "author":"0",
          "description":"",
          "caption":"",
          "name":"54e80dd703fb02d789b1179fa8fdbcaa-png",
          "date":"2017-09-11 15:17:36",
          "modified":"2017-09-12 15:08:49",
          "mime_type":"image/png",
          "type":"image",
          "icon":"http://shortlist.dev/wp/wp-includes/images/media/default.png",
          "width":980,
          "height":551,
          "sizes":{

          }
        }
      },

```

It's a required field but users without images:
```js
"acf": [],
```

### CODE REVIEW

**Comment by leonoragilmour** [comment]
is `$acf = apply_filters('init/acf', $acf);` the right hook i wonder

**Comment by jonsherrard** [comment]
Regarding the filter - what do we do on other custom fields?

**Comment by leonoragilmour** [comment]
Oooh does it maybe not even need a filter? It just needs to be registered...

**Comment by jonsherrard** [comment]
Potentially yeah

**Pull request merged**
